workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: never  # Prevent pipeline run for push event
    - when: always # Run pipeline for all other cases

stages:
  - build

build_image:
  stage: build
  image: docker:20.10.17
  services:
    - name: docker:20.10.17-dind
      alias: docker
      command: [ "--tls=false" ]
  variables:
    # using "docker" as the host is only possible if you alias the service
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - set -o allexport
    - source $ENV_GITLAB
    - set +o allexport
  script: # authenticate in dockerhub registry from inside the executor
    - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PASSWORD $DOCKER_REGISTRY
    - export PACKAGE_VERSION=$(grep -m 1 version ./backend/pyproject.toml | tr -s ' ' | tr -d '"' | tr -d "'" | cut -d' ' -f3)
    - echo $PACKAGE_VERSION
    - export APP_VERSION=$PACKAGE_VERSION.$CI_PIPELINE_IID
    - docker build -t $CI_REGISTRY_IMAGE:$APP_VERSION - f Dokerfile .
    - docker push $CI_REGISTRY_IMAGE:$APP_VERSION

