version: "3.5"


services:
  redis:
    image: redis
    container_name: redis_dev
    ports:
      - "6379:6379"
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data

  postgres:
    image: postgres
    restart: unless-stopped
    container_name: postgres_dev
    ports:
      - "5432:5432"
    env_file:
      - .env.dev.postgres
    volumes:
      - ./postgres-init-db.sh:/docker-entrypoint-initdb.d/postgres-init-db.sh
      - ./postgres_data_dev/:/var/lib/postgresql/data


#  adminer:
#    image: adminer
#    container_name: adminer_dev
#    restart: unless-stopped
#    ports:
#      - 8080:8080

# TODO containerize celery worker

volumes:
  redis_data:


