version: "3.5"


services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data

volumes:
  redis_data:

