version: "3.5"


services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    command: [ 'redis-server', '--appendonly', 'yes' ]
    volumes:
      - redis_data:/data

  flask_backend:
    container_name: flask_backend
    image: flask_backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    env_file:
      - backend/src/.flaskenv
      - backend/src/.env
    volumes:
      - sqlite_data:/app/app.sqlite



volumes:
  redis_data:
  sqlite_data:

